import { Web3Modal } from '../lib/wagmi';
import { Web5Component } from '../lib/web5/web5-context';
import './global.css';

export const metadata = {
  title: 'Welcome to zknw-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-slate-50">
        <Web3Modal>
          <Web5Component>{children}</Web5Component>
        </Web3Modal>
      </body>
    </html>
  );
}
