import { Web3Modal } from '../lib/wagmi';
import './global.css';

export const metadata = {
  title: 'Welcome to zknw-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='bg-background text-slate-50'>
        <Web3Modal>
          {children}
        </Web3Modal>
      </body>
    </html>
  );
}
